"""Policy Store: SQLite-backed persistent storage for workflow policies.

Policies are atomic trigger-rule pairs generated by the Reviewer and
injected into Planner specs to prevent recurring failures.

Schema
------
policies     : structured policy data (status, strength, rules, etc.)
policies_vec : vector embeddings for semantic search (via sqlite-vec)

The vector table is optional — if sqlite-vec cannot be loaded the store
degrades gracefully to tag/status-based filtering only.
"""

import json
import logging
import sqlite3
import uuid
from dataclasses import dataclass, field
from datetime import UTC, datetime
from pathlib import Path

logger = logging.getLogger(__name__)

# Status lifecycle: draft → active → archived / rejected
STATUS_DRAFT = "draft"
STATUS_ACTIVE = "active"
STATUS_ARCHIVED = "archived"
STATUS_REJECTED = "rejected"

STRENGTH_LOW = "low"
STRENGTH_MEDIUM = "medium"
STRENGTH_HIGH = "high"

_STRENGTH_ORDER = {STRENGTH_LOW: 0, STRENGTH_MEDIUM: 1, STRENGTH_HIGH: 2}

_CREATE_POLICIES = """
CREATE TABLE IF NOT EXISTS policies (
    id                 TEXT PRIMARY KEY,
    title              TEXT NOT NULL,
    why                TEXT NOT NULL DEFAULT '',
    status             TEXT NOT NULL DEFAULT 'draft',
    strength           TEXT NOT NULL DEFAULT 'medium',
    trigger_tags       TEXT,          -- JSON array of strings
    trigger_conditions TEXT,          -- JSON array of strings
    rules              TEXT NOT NULL DEFAULT '[]',  -- JSON array of strings
    source_task        TEXT,          -- GitHub issue number (string)
    approved_by        TEXT,
    fired_count        INTEGER DEFAULT 0,
    accepted_count     INTEGER DEFAULT 0,
    reverted_count     INTEGER DEFAULT 0,
    created_at         TEXT DEFAULT (datetime('now')),
    updated_at         TEXT DEFAULT (datetime('now'))
);
"""


@dataclass
class Policy:
    """A single policy record."""

    id: str
    title: str
    why: str
    status: str
    strength: str
    rules: list[str]
    trigger_tags: list[str] = field(default_factory=list)
    trigger_conditions: list[str] = field(default_factory=list)
    source_task: str | None = None
    approved_by: str | None = None
    fired_count: int = 0
    accepted_count: int = 0
    reverted_count: int = 0
    created_at: str = ""
    updated_at: str = ""


class PolicyStore:
    """
    SQLite-backed policy store with optional sqlite-vec vector search.

    Thread/process safety: WAL mode allows concurrent reads with one writer.
    Multiple agents can read simultaneously; writes are serialized by SQLite.
    """

    def __init__(self, db_path: str):
        if not isinstance(db_path, str):
            raise TypeError(
                f"PolicyStore db_path must be a str, got {type(db_path).__name__}: {db_path!r}"
            )
        self.db_path = str(Path(db_path).expanduser())
        Path(self.db_path).parent.mkdir(parents=True, exist_ok=True)

        self._conn = sqlite3.connect(self.db_path, check_same_thread=False)
        self._conn.row_factory = sqlite3.Row
        self._conn.execute("PRAGMA journal_mode=WAL")
        self._conn.execute("PRAGMA foreign_keys=ON")
        self._conn.execute(_CREATE_POLICIES)
        self._conn.commit()

        self._vec_enabled = self._try_load_sqlite_vec()

    # ── Public API ────────────────────────────────────────────────────────────

    def insert_candidate(
        self,
        candidate: dict,
        source_task: str | None = None,
    ) -> str:
        """
        Save a policy candidate from a Reviewer as status='draft'.

        Args:
            candidate: dict with keys title, why, rules, trigger_tags,
                       trigger_conditions, strength
            source_task: GitHub issue number string (e.g. "42")

        Returns:
            The new policy ID.
        """
        policy_id = f"policy_{uuid.uuid4().hex[:16]}"
        now = datetime.now(UTC).isoformat()

        self._conn.execute(
            """
            INSERT INTO policies
                (id, title, why, status, strength,
                 trigger_tags, trigger_conditions, rules,
                 source_task, created_at, updated_at)
            VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
            """,
            (
                policy_id,
                candidate.get("title", ""),
                candidate.get("why", ""),
                STATUS_DRAFT,
                candidate.get("strength", STRENGTH_MEDIUM),
                json.dumps(candidate.get("trigger_tags", [])),
                json.dumps(candidate.get("trigger_conditions", [])),
                json.dumps(candidate.get("rules", [])),
                source_task,
                now,
                now,
            ),
        )
        self._conn.commit()
        logger.info(
            f"Policy candidate saved: {policy_id} — {candidate.get('title', '')}"
        )
        return policy_id

    def approve(self, policy_id: str, approved_by: str = "human") -> bool:
        """
        Promote a draft policy to active.

        Returns True if the policy was found and updated.
        """
        now = datetime.now(UTC).isoformat()
        cursor = self._conn.execute(
            """
            UPDATE policies
            SET status = ?, approved_by = ?, updated_at = ?
            WHERE id = ? AND status = ?
            """,
            (STATUS_ACTIVE, approved_by, now, policy_id, STATUS_DRAFT),
        )
        self._conn.commit()
        found = cursor.rowcount > 0
        if found:
            logger.info(f"Policy approved: {policy_id} by {approved_by}")
        else:
            logger.warning(f"Policy not found or not in draft state: {policy_id}")
        return found

    def query(
        self,
        status: str = STATUS_ACTIVE,
        strength: str | None = None,
        tags: list[str] | None = None,
        limit: int = 50,
    ) -> list[Policy]:
        """
        Query policies by status and optional filters.

        Args:
            status: Filter by status ('draft', 'active', etc.)
            strength: Minimum strength ('low', 'medium', 'high')
            tags: Return policies whose trigger_tags overlap with these tags
            limit: Maximum number of results

        Returns:
            List of Policy objects ordered by updated_at descending.
        """
        rows = self._conn.execute(
            """
            SELECT * FROM policies
            WHERE status = ?
            ORDER BY updated_at DESC
            LIMIT ?
            """,
            (status, limit),
        ).fetchall()

        policies = [self._row_to_policy(r) for r in rows]

        if strength is not None:
            min_order = _STRENGTH_ORDER.get(strength, 0)
            policies = [
                p for p in policies if _STRENGTH_ORDER.get(p.strength, 0) >= min_order
            ]

        if tags:
            tag_set = set(tags)
            policies = [p for p in policies if tag_set & set(p.trigger_tags)]

        return policies

    def get(self, policy_id: str) -> Policy | None:
        """Fetch a single policy by ID."""
        row = self._conn.execute(
            "SELECT * FROM policies WHERE id = ?", (policy_id,)
        ).fetchone()
        return self._row_to_policy(row) if row else None

    def increment_fired(self, policy_id: str) -> None:
        """Record that this policy was injected into a spec."""
        self._conn.execute(
            "UPDATE policies SET fired_count = fired_count + 1, updated_at = datetime('now') WHERE id = ?",
            (policy_id,),
        )
        self._conn.commit()

    def increment_accepted(self, policy_id: str) -> None:
        """Record that a PR using this policy was approved."""
        self._conn.execute(
            "UPDATE policies SET accepted_count = accepted_count + 1, updated_at = datetime('now') WHERE id = ?",
            (policy_id,),
        )
        self._conn.commit()

    def close(self) -> None:
        self._conn.close()

    # ── Private ───────────────────────────────────────────────────────────────

    def _try_load_sqlite_vec(self) -> bool:
        """Attempt to load sqlite-vec extension. Returns True on success."""
        try:
            import sqlite_vec

            self._conn.enable_load_extension(True)
            sqlite_vec.load(self._conn)
            self._conn.enable_load_extension(False)
            logger.info("sqlite-vec loaded — vector search enabled")
            return True
        except Exception as e:
            logger.debug(f"sqlite-vec not available, vector search disabled: {e}")
            return False

    def _row_to_policy(self, row: sqlite3.Row) -> Policy:
        return Policy(
            id=row["id"],
            title=row["title"],
            why=row["why"],
            status=row["status"],
            strength=row["strength"],
            rules=json.loads(row["rules"] or "[]"),
            trigger_tags=json.loads(row["trigger_tags"] or "[]"),
            trigger_conditions=json.loads(row["trigger_conditions"] or "[]"),
            source_task=row["source_task"],
            approved_by=row["approved_by"],
            fired_count=row["fired_count"] or 0,
            accepted_count=row["accepted_count"] or 0,
            reverted_count=row["reverted_count"] or 0,
            created_at=row["created_at"] or "",
            updated_at=row["updated_at"] or "",
        )
